quarkus.application.name=records-command-service
quarkus.http.port=8081

quarkus.log.level=INFO
quarkus.log.console.json=true
quarkus.log.console.json.exception-output-type=formatted
%test.quarkus.log.console.json=false
%dev.quarkus.log.console.json=false
