quarkus.application.name=records-query-service
quarkus.http.port=8082

quarkus.log.level=INFO
quarkus.log.console.json=true
quarkus.log.console.json.exception-output-type=formatted
%test.quarkus.log.console.json=false
%dev.quarkus.log.console.json=false
